# Project information
## 左上のサイト名
site_name: test1111
site_url: https://kzrashi.github.io/python-grammer/
site_author: kzrashi
site_description: >-
  This site illustrates grammer of python programing language for beginners.

# Repository
## GitのURL
repo_url: https://github.com/kzrashi/python-grammer
## 表示文字列
repo_name: kzrashi/python-grammer


# フッター部
## Copyright
copyright: "Copyright © 2021 -  kzrashi All Rights Reserved."


# Configuration
theme:
  name: material
  language: ja
  # # 左上のアイコン
  # logo: assets/python_94570.svg
  # icon:
  #   # Gitリポジトリエリアのアイコン
  #   repo: fontawesome/brands/github    # icon:
  #   #   logo: assets/python_94570.svg
  # #        repo: fontawesome/brands/git-alt

  # ファビコン
  favicon: assets/python_94570.svg

# Plugins
plugins:
   # 検索機能(英語・日本語)
   - search:
      lang:
        - en
        - ja


# Extensions
markdown_extensions:
  # code block
  # - pymdownx.highlight:
  #     anchor_linenums: true
  # - pymdownx.inlinehilite
  # - pymdownx.snippets

  #  Diagrams for Mermaid
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # mathjax(数式)
  - pymdownx.arithmatex:
      generic: true



# extra
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



# # Google Analytics
# google_analytics:
#   - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#   - auto
